### ISSUE TITLE
the color white

### ISSUE THREAD

**Issue by kmatze** [Dryja/AnimatedGifC#1]
Hi Dryja,
i have found your formidable tiny gif lib and want to try create a tcl packege with this under windows. It works fine. Thx.

"small" problem with the colortable i have:

if i use the the function GIF_SetColor(3, 255, 255, 255);

i get a gray color:

here is the pure c-code for an example:
-------------------------------------------
#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>

#include "gifsave.h"

#define WIDTH        320
#define HEIGHT       240
#define NUMCOLORS      4  /* must change DumpImage if this is changed */
#define COLORRES       2  /* number of bits for each primary color */
#define FILENAME "example1.gif"

/* the image buffer */
static unsigned char Screen[WIDTH][HEIGHT];

/**************************************************************************
 *                                                                        *
 *                   P R I V A T E    F U N C T I O N S                   *
 *                                                                        *
 **************************************************************************/

/*-------------------------------------------------------------------------
 *
 *  NAME          GetPixel
 *
 *  DESCRIPTION   Callback function fetching a pixel value from the buffer.
 *
 *  INPUT         x,y     the location of the pixel
 *
 *  RETURNS       Pixel value, in the range [0, NUMCOLORS).
 */
static int GetPixel(int x, int y)
{
    return Screen[x][y];
}

/*-------------------------------------------------------------------------
 *
 *  NAME          DrawImage
 *
 *  DESCRIPTION   Produces some output inn the image buffer.
 */
static void
DrawColor(int color)
{
    int i,j;
    for(i=0;i<WIDTH;i++){
        for(j=0;j<HEIGHT;j++){
            Screen[i][j] = color;
        }
    }
}

int
main(void)
{
    /* create and set up the GIF-file */
    GIF_Create(FILENAME, WIDTH, HEIGHT, NUMCOLORS, COLORRES);
    /* define a few colors matching the pixel values used */
    GIF_SetColor(0, 0, 0, 0);        // black
    GIF_SetColor(1, 255, 0, 0);      // red
    GIF_SetColor(2, 0, 255, 0);      // green
    GIF_SetColor(3, 255, 255, 255);  // white

    GIF_WriteHeader(0);

    DrawColor(3);
    GIF_AddFrame(0, 0, -1, -1,100, GetPixel);
    DrawColor(2);
    GIF_AddFrame(0, 0, -1, -1,100, GetPixel);
    DrawColor(1);
    GIF_AddFrame(0, 0, -1, -1,100, GetPixel);
    DrawColor(0);
    GIF_AddFrame(0, 0, -1, -1,100, GetPixel);
    DrawColor(3);
    GIF_AddFrame(0, 0, -1, -1,100, GetPixel);

    GIF_Close();

    return 0;
}
---------------------------------------------
and the result:
![example1](https://cloud.githubusercontent.com/assets/27211712/25181164/e4471d34-2510-11e7-915d-f43c84454a37.gif)

the other colors are ok.

What i do wrong?

thx for your help. Greetings - kmatze

**Comment by Dryja** [comment]
Hey,
I would suggest changing COLORRES to 8 bits. You need 24bit to get true RGB. Now you are playing with Grayscale (I am sure you can see that red and green color is litte bit gray).

**Comment by Dryja** [comment]
My result with `COLORRES 8`
![example](https://cloud.githubusercontent.com/assets/2962187/25182588/693c26ac-2515-11e7-9c01-72aee89004a0.gif)

**Comment by kmatze** [comment]
Hi Dryja,
thanks for your fast answer,
i thought that the color res is the definition of the length of color  
table.
is the colortable static length or dynamicle?

i will try now with colorres 8 and will you inform about my result.

Greetings - kmatze


Am 19.04.2017, 15:33 Uhr, schrieb Hubert Dryja <notifications@github.com>:

>
> My result with COLORRES 8
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/

**Comment by Dryja** [comment]
color table size is definied here `NUMCOLORS 4`

**Comment by kmatze** [comment]
now, that works pretty.
thank you very much.
Later, i will load my result to github ;-)
Greetings - kmatze
