### ISSUE TITLE
local color palette?

### ISSUE THREAD

**Issue by kmatze** [Dryja/AnimatedGifC#2]
Hi Dryja,
my tcl package is ready now and works fine.

A little question:
I you make develop next version of AnimatedGifC, can you create the feature of local palette, maybe?
I'm not so firm in C.

The added feature should be: 
GIF_AddFrame(0, 0, -1, -1, delay, localpalette, mkGetPixel)

That will be fine for realtime creating images because new colors can added in a open stream (if the local palette has free places and is great enough).

Thanks a lot and greetings - kmatze

**Comment by Dryja** [comment]
Hi kmatze,
I am happy that your tcl package is fine now. 

As for the lib. I am not planning to add something new. 
Creating real-time palette is not possible, because the gif requires to define a global palette at the beginning.

**Comment by kmatze** [comment]
Hi Dryja,
that's ok. But only for you info a little bit from gif89a spezification for local color table for a frame (see image block, offset 8ff):

**GIF Header**
```
Offset   Length   Contents
  0      3 bytes  "GIF"
  3      3 bytes  "87a" or "89a"
  6      2 bytes  <Logical Screen Width>
  8      2 bytes  <Logical Screen Height>
 10      1 byte   bit 0:    Global Color Table Flag (GCTF)
                  bit 1..3: Color Resolution
                  bit 4:    Sort Flag to Global Color Table
                  bit 5..7: Size of Global Color Table: 2^(1+n)
 11      1 byte   <Background Color Index>
 12      1 byte   <Pixel Aspect Ratio>
 13      ? bytes  <Global Color Table(0..255 x 3 bytes) if GCTF is one>
         ? bytes  <Blocks>
         1 bytes  <Trailer> (0x3b)
```

**Image Block** = frame
```
Offset   Length   Contents
  0      1 byte   Image Separator (0x2c)
  1      2 bytes  Image Left Position
  3      2 bytes  Image Top Position
  5      2 bytes  Image Width
  7      2 bytes  Image Height
  8      1 byte   bit 0:    Local Color Table Flag (LCTF)
                  bit 1:    Interlace Flag
                  bit 2:    Sort Flag
                  bit 2..3: Reserved
                  bit 4..7: Size of Local Color Table: 2^(1+n)
         ? bytes  Local Color Table(0..255 x 3 bytes) if LCTF is one
         1 byte   LZW Minimum Code Size
[ // Blocks
         1 byte   Block Size (s)
        (s)bytes  Image Data
]*
         1 byte   Block Terminator(0x00)
```
found at http://www.onicos.com/staff/iz/formats/gif.html

the complete specification you can find here https://www.w3.org/Graphics/GIF/spec-gif89a.txt (loacal color table, pager 13).

greetings - kmatze
